# Generated by Django 4.0.4 on 2022-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ФИ')),
                ('position', models.CharField(max_length=60, verbose_name='Должность')),
                ('subject', models.CharField(max_length=60, verbose_name='Дисциплина')),
                ('cabinet', models.IntegerField(verbose_name='Кабинет')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
