# Generated by Django 4.0.4 on 2022-04-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pz12', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Дисциплина')),
                ('tcode', models.IntegerField(verbose_name='Учебный код')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pz12.subjects'),
        ),
    ]
